package org.nazarius.VovkORM.sql.dialect;

import java.util.HashMap;
import java.util.Map;

public class OracleDialect implements Dialect {
    private static final Map<Class<?>, String> TYPE_MAPPING = new HashMap<>();

    static {
        TYPE_MAPPING.put(Integer.class, "NUMBER(10)");
        TYPE_MAPPING.put(int.class, "NUMBER(10)");
        TYPE_MAPPING.put(Long.class, "NUMBER(19)");
        TYPE_MAPPING.put(long.class, "NUMBER(19)");
        TYPE_MAPPING.put(Boolean.class, "NUMBER(1)");
        TYPE_MAPPING.put(boolean.class, "NUMBER(1)");
        TYPE_MAPPING.put(String.class, "VARCHAR2(255)");
    }

    @Override
    public String getIdentityColumnString() {
        return "GENERATED BY DEFAULT AS IDENTITY";
    }

    @Override
    public String getLimitOffsetClause(long limit, long offset) {
        StringBuilder sql = new StringBuilder();

        if (offset > 0) {
            sql.append("OFFSET ").append(offset).append(" ROWS ");
        }

        if (limit > 0) {
            sql.append("FETCH FIRST ").append(limit).append(" ROWS ONLY");
        }

        return sql.toString().trim();
    }

    @Override
    public String getColumnType(Class<?> javaType) {
        return TYPE_MAPPING.getOrDefault(javaType, "VARCHAR2(255)");
    }
}
